/**
 * @fileoverview Sidebar configuration generator
 * @module generators/SidebarGenerator
 */

const { getChapterName } = require('../config/chapters');
const { sortChapterKeys, generateSidebarLabel } = require('../utils/helpers');

/**
 * Generator for Docusaurus sidebar configuration
 */
class SidebarGenerator {
  /**
   * Create a sidebar generator
   * @param {Object} config - Application configuration
   */
  constructor(config) {
    this.config = config;
  }

  /**
   * Generate sidebar configuration content
   * @param {Map<string, Set<string>>} byChapter - Map of chapter -> Set of program IDs
   * @param {Map<string, Object>} programFiles - Map of programId -> { programInfo, files }
   * @returns {string} JavaScript module content for sidebars.js
   */
  generate(byChapter, programFiles) {
    const categories = Array.from(byChapter.keys())
      .sort(sortChapterKeys)
      .map(chapterNum => this.generateCategory(chapterNum, byChapter.get(chapterNum), programFiles));

    return `/**
 * Auto-generated sidebar configuration
 * Generated by: Applied QM Documentation Generator v${this.config.version}
 * Last updated: ${new Date().toISOString()}
 *
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next generation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '📖 Introduction',
    },
    {
      type: 'category',
      label: '📚 Programs by Chapter',
      collapsed: false,
      items: [
${categories.map(cat => `        ${JSON.stringify(cat, null, 2).split('\n').join('\n        ')}`).join(',\n')},
      ],
    },
    {
      type: 'category',
      label: '🛠️ Developer Guide',
      collapsed: true,
      items: [
        { type: 'doc', id: 'developer-guide/index', label: 'Overview' },
        { type: 'doc', id: 'developer-guide/changelog', label: '📝 Changelog' },
        {
          type: 'category',
          label: 'Configuration',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/config/index', label: 'Config Module' },
          ],
        },
        {
          type: 'category',
          label: 'Utilities',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/utils/index', label: 'Utils Module' },
          ],
        },
        {
          type: 'category',
          label: 'Generators',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/generators/index', label: 'Generators Module' },
          ],
        },
        {
          type: 'category',
          label: 'Services',
          collapsed: true,
          items: [
            { type: 'doc', id: 'developer-guide/services/index', label: 'Services Module' },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
`;
  }

  /**
   * Generate a chapter category for the sidebar
   * @param {string} chapterNum - Chapter number or 'utilities'
   * @param {Set<string>} programs - Set of program IDs
   * @param {Map<string, Object>} programFiles - Map of programId -> { programInfo, files }
   * @returns {Object} Sidebar category object
   */
  generateCategory(chapterNum, programs, programFiles) {
    const items = [];

    // Sort programs and generate items for each file
    const sortedPrograms = Array.from(programs).sort();

    for (const programId of sortedPrograms) {
      const programData = programFiles.get(programId);
      if (!programData) continue;

      const { files } = programData;

      // Sort files by type: matlab first, then latex, then pdf, then others
      const typeOrder = ['matlab', 'latex', 'pdf', 'html', 'ipynb', 'text'];
      const sortedFiles = [...files].sort((a, b) => {
        const aIdx = typeOrder.indexOf(a.config.type);
        const bIdx = typeOrder.indexOf(b.config.type);
        return aIdx - bIdx;
      });

      // Generate sidebar item for each file
      for (const file of sortedFiles) {
        items.push(this.generateFileItem(chapterNum, programId, file));
      }
    }

    const label = chapterNum === 'utilities'
      ? `🔧 ${getChapterName(chapterNum)}`
      : `Ch ${parseInt(chapterNum, 10)}: ${getChapterName(chapterNum)}`;

    return {
      type: 'category',
      label,
      collapsed: true,
      items,
    };
  }

  /**
   * Generate a single file item for the sidebar
   * @param {string} chapterNum - Chapter number or 'utilities'
   * @param {string} programId - Program ID
   * @param {Object} file - File info with filename and config
   * @returns {Object} Sidebar doc item object
   */
  generateFileItem(chapterNum, programId, file) {
    const folder = chapterNum === 'utilities' ? 'utilities' : `chapter${chapterNum}`;
    const { config } = file;

    // Use shared helper to generate consistent sidebar label
    const label = generateSidebarLabel(programId, chapterNum, config.type);

    return {
      type: 'doc',
      id: `${folder}/${programId}/${programId}_${config.type}`,
      label,
    };
  }
}

module.exports = SidebarGenerator;
